# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import jab_wrapper_pb2 as jab__wrapper__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jab_wrapper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JabServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SelectWindow = channel.unary_unary(
                '/jab_wrapper.JabService/SelectWindow',
                request_serializer=jab__wrapper__pb2.SelectWindowRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.SelectWindowResponse.FromString,
                _registered_method=True)
        self.FindElements = channel.unary_unary(
                '/jab_wrapper.JabService/FindElements',
                request_serializer=jab__wrapper__pb2.FindElementsRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.FindElementsResponse.FromString,
                _registered_method=True)
        self.ClickElement = channel.unary_unary(
                '/jab_wrapper.JabService/ClickElement',
                request_serializer=jab__wrapper__pb2.ClickElementRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.ClickElementResponse.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/jab_wrapper.JabService/TypeText',
                request_serializer=jab__wrapper__pb2.TypeTextRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.TypeTextResponse.FromString,
                _registered_method=True)
        self.GetElementText = channel.unary_unary(
                '/jab_wrapper.JabService/GetElementText',
                request_serializer=jab__wrapper__pb2.GetElementTextRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.GetElementTextResponse.FromString,
                _registered_method=True)
        self.GetVersionInfo = channel.unary_unary(
                '/jab_wrapper.JabService/GetVersionInfo',
                request_serializer=jab__wrapper__pb2.GetVersionInfoRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.GetVersionInfoResponse.FromString,
                _registered_method=True)
        self.ListWindows = channel.unary_unary(
                '/jab_wrapper.JabService/ListWindows',
                request_serializer=jab__wrapper__pb2.ListWindowsRequest.SerializeToString,
                response_deserializer=jab__wrapper__pb2.ListWindowsResponse.FromString,
                _registered_method=True)


class JabServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SelectWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetElementText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JabServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SelectWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectWindow,
                    request_deserializer=jab__wrapper__pb2.SelectWindowRequest.FromString,
                    response_serializer=jab__wrapper__pb2.SelectWindowResponse.SerializeToString,
            ),
            'FindElements': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElements,
                    request_deserializer=jab__wrapper__pb2.FindElementsRequest.FromString,
                    response_serializer=jab__wrapper__pb2.FindElementsResponse.SerializeToString,
            ),
            'ClickElement': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickElement,
                    request_deserializer=jab__wrapper__pb2.ClickElementRequest.FromString,
                    response_serializer=jab__wrapper__pb2.ClickElementResponse.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=jab__wrapper__pb2.TypeTextRequest.FromString,
                    response_serializer=jab__wrapper__pb2.TypeTextResponse.SerializeToString,
            ),
            'GetElementText': grpc.unary_unary_rpc_method_handler(
                    servicer.GetElementText,
                    request_deserializer=jab__wrapper__pb2.GetElementTextRequest.FromString,
                    response_serializer=jab__wrapper__pb2.GetElementTextResponse.SerializeToString,
            ),
            'GetVersionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersionInfo,
                    request_deserializer=jab__wrapper__pb2.GetVersionInfoRequest.FromString,
                    response_serializer=jab__wrapper__pb2.GetVersionInfoResponse.SerializeToString,
            ),
            'ListWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWindows,
                    request_deserializer=jab__wrapper__pb2.ListWindowsRequest.FromString,
                    response_serializer=jab__wrapper__pb2.ListWindowsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jab_wrapper.JabService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jab_wrapper.JabService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JabService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SelectWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/SelectWindow',
            jab__wrapper__pb2.SelectWindowRequest.SerializeToString,
            jab__wrapper__pb2.SelectWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/FindElements',
            jab__wrapper__pb2.FindElementsRequest.SerializeToString,
            jab__wrapper__pb2.FindElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/ClickElement',
            jab__wrapper__pb2.ClickElementRequest.SerializeToString,
            jab__wrapper__pb2.ClickElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/TypeText',
            jab__wrapper__pb2.TypeTextRequest.SerializeToString,
            jab__wrapper__pb2.TypeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetElementText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/GetElementText',
            jab__wrapper__pb2.GetElementTextRequest.SerializeToString,
            jab__wrapper__pb2.GetElementTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/GetVersionInfo',
            jab__wrapper__pb2.GetVersionInfoRequest.SerializeToString,
            jab__wrapper__pb2.GetVersionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jab_wrapper.JabService/ListWindows',
            jab__wrapper__pb2.ListWindowsRequest.SerializeToString,
            jab__wrapper__pb2.ListWindowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
